/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: 00e01df6b95a52d1342c0c76d2f71520)
interface __BaseEnv_Env {
	LIVEKIT_URL: "wss://kpnc-projects-01lpu7f8.livekit.cloud";
	ALLOWED_ORIGINS: "https://kpnc-meet.pages.dev,http://localhost:3000,http://localhost:8788";
	ROOM_PREFIX: "";
	LIVEKIT_API_KEY: string;
	LIVEKIT_API_SECRET: string;
	ROOMS: DurableObjectNamespace<import("./src/index").RoomCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RoomCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LIVEKIT_URL" | "ALLOWED_ORIGINS" | "ROOM_PREFIX" | "LIVEKIT_API_KEY" | "LIVEKIT_API_SECRET">> {}
}
